import * as config from '@lvce-editor/eslint-config'

export default [
  ...config.default,
  {
    files: ['**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      'no-case-declarations': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/restrict-plus-operands': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/no-dynamic-delete': 'off',
      '@typescript-eslint/prefer-readonly-parameter-types': 'off',
      'prefer-destructuring': 'off',
      'no-console': 'off',
      'unicorn/no-for-loop': 'off',

      '@typescript-eslint/no-deprecated': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      'unicorn/prefer-global-this': 'off',
      'perfectionist/sort-imports': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      'unicorn/empty-brace-spaces': 'off',
      'no-useless-escape': 'off',
      'unicorn/error-message': 'off',
      'jest/no-identical-title': 'off',
      'jest/no-disabled-tests': 'off',
      'jest/expect-expect': 'off',
      '@typescript-eslint/unbound-method': 'off',
      'unicorn/prefer-spread': 'off',
      '@typescript-eslint/await-thenable': 'off',
      'unicorn/no-empty-file': 'off',
      'no-fallthrough': 'off',
      'unicorn/prefer-query-selector': 'off',
      'unicorn/no-array-method-this-argument': 'off',
      'unicorn/prefer-export-from': 'off',
      'unicorn/prefer-regexp-test': 'off',
      'no-empty': 'off',
      'no-duplicate-case': 'off',
      'unicorn/numeric-separators-style': 'off',
      'unicorn/consistent-function-scoping': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
    },
  },
]
